/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.beans.PropertyChangeListener;
import java.beans.PropertyChangeSupport;
import javax.swing.JOptionPane;
import javax.swing.table.AbstractTableModel;

/**
 *
 * @author i.mcolo
 */
public class MainView extends javax.swing.JFrame {
// Attributs
// Liste des abonnés

    private PropertyChangeSupport listeners = new PropertyChangeSupport(this);

// Méthode publique permettant d'ajouter un abonné
    @Override
    public void addPropertyChangeListener(PropertyChangeListener l) {
        listeners.addPropertyChangeListener(l);
    }

    // Exemple de méthode exécutée sur un évènement clic
    /**
     * Creates new form MainView
     */
    public MainView() {
        initComponents();
    }

    public void setTableModel(AbstractTableModel tableModel) {
        this.listeUser.setModel(tableModel);
        this.listeUser.removeColumn(this.listeUser.getColumn("id"));
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listeUser = new javax.swing.JTable();
        ajoutUtilisateur = new javax.swing.JButton();
        modifierButton1 = new javax.swing.JButton();
        deleteButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        listeUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(listeUser);

        ajoutUtilisateur.setText("Ajouter un utilisateur");
        ajoutUtilisateur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajoutUtilisateurActionPerformed(evt);
            }
        });

        modifierButton1.setText("Modifier");
        modifierButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifierButton1ActionPerformed(evt);
            }
        });

        deleteButton1.setText("supprimer");
        deleteButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addComponent(ajoutUtilisateur)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(deleteButton1)
                            .addComponent(modifierButton1))
                        .addGap(47, 47, 47)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(154, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(144, 144, 144))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(ajoutUtilisateur)
                        .addGap(18, 18, 18)
                        .addComponent(modifierButton1)
                        .addGap(18, 18, 18)
                        .addComponent(deleteButton1)
                        .addGap(327, 327, 327))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ajoutUtilisateurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajoutUtilisateurActionPerformed
        // TODO add your handling code here:
        listeners.firePropertyChange("btnAjoutUtilisateurClick", null, null);
    }//GEN-LAST:event_ajoutUtilisateurActionPerformed

    private void modifierButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifierButton1ActionPerformed
        // TODO add your handling code here:
        listeners.firePropertyChange("btnModifierUtilisateurClick", null, null);
    }//GEN-LAST:event_modifierButton1ActionPerformed

    private void deleteButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButton1ActionPerformed
        // TODO add your handling code here:
        int reponse = JOptionPane.showConfirmDialog(null, "Etes vous sur", "confirmation", JOptionPane.YES_NO_OPTION);
            if(reponse == JOptionPane.YES_OPTION){
                listeners.firePropertyChange("btnDeleteUtilisateurClick", null, null);
            }
            else{
                System.out.println("suppression annulée ");
            }
    }//GEN-LAST:event_deleteButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ajoutUtilisateur;
    private javax.swing.JButton deleteButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable listeUser;
    private javax.swing.JButton modifierButton1;
    // End of variables declaration//GEN-END:variables

    public Integer getSelectedIdModifier() {
        return (Integer) this.listeUser.getModel().getValueAt(this.listeUser.getSelectedRow(), 0);

    }

    public String getSelectedNomModifier() {
        return (String) this.listeUser.getModel().getValueAt(this.listeUser.getSelectedRow(), 1);

    }

    public String getSelectedprenomModifier() {
        return (String) this.listeUser.getModel().getValueAt(this.listeUser.getSelectedRow(), 2);

    }

    public String getSelectedEmailModifier() {
        return (String) this.listeUser.getModel().getValueAt(this.listeUser.getSelectedRow(), 3);

    }

}
