package view;

import java.beans.PropertyChangeListener;
import java.beans.PropertyChangeSupport;
import java.util.ArrayList;
import model.UserListModel;
import model.Utilisateur;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
/**
 *
 * @author i.mcolo
 */
public class ModifDialog extends javax.swing.JDialog {

    private ArrayList<Utilisateur> utilisateurs = new ArrayList<Utilisateur>();
    private Integer id;
    private UserListModel userList;
    private MainView view;
    
    
    /**
     * Creates new form ModifDialog
     */
    public ModifDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    //!!\\ permet de faire l,abonnement avec le Controleur//!!\\
    private PropertyChangeSupport listeners = new PropertyChangeSupport(this);

    public void addPropertyChangeListener(PropertyChangeListener l) {
        this.listeners.addPropertyChangeListener(l);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nomTextField1 = new javax.swing.JTextField();
        prenomTextField2 = new javax.swing.JTextField();
        emailTextField3 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        valideModifToggleButton1 = new javax.swing.JToggleButton();
        communeTextField1 = new javax.swing.JTextField();
        communeLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        nomTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomTextField1ActionPerformed(evt);
            }
        });

        emailTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTextField3ActionPerformed(evt);
            }
        });

        jLabel1.setText("Nom");

        jLabel2.setText("Prenom");

        jLabel3.setText("Email");

        valideModifToggleButton1.setText("Valider la modification");
        valideModifToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valideModifToggleButton1ActionPerformed(evt);
            }
        });

        communeLabel4.setText("Commune");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(communeLabel4))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(valideModifToggleButton1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(communeTextField1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(emailTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                        .addComponent(prenomTextField2)
                        .addComponent(nomTextField1)))
                .addContainerGap(175, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prenomTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(communeTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(communeLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(valideModifToggleButton1)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nomTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomTextField1ActionPerformed

    private void emailTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTextField3ActionPerformed

    private void valideModifToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valideModifToggleButton1ActionPerformed
        // TODO add your handling code here:
        listeners.firePropertyChange("btnValiderModifierClick", null, null);
    }//GEN-LAST:event_valideModifToggleButton1ActionPerformed

//        public Integer getSelectedIdModifier(){
//        return (Integer) this.userList.getModel().getValueAt(this.userList.getSelectedRow(),0);
//        
//        }
//    
//        public String getSelectedNomModifier(){
//        return (String) this.utilisateurs.getModel().getValue(this.utilisateurs.getSelectedRow(),1);
//        
//        }
//        
//        public String getSelectedprenomModifier(){
//        return (String) this.utilisateurs.getModel().getValue(this.utilisateurs.getSelectedRow(),2);
//        
//        }
//        public String getSelectedEmailModifier(){
//        return (String) this.utilisateurs.getModel().getValue(this.utilisateurs.getSelectedRow(),3);
//        
//        }
        
        
        public void setId(Integer id){
        
            this.id=id;
        
        }
        public Integer getId(){
        
            return this.id;
        
        }
        
        public void setNom(String nom){
        
            this.nomTextField1.setText(nom);
        
        }
        
        public void setPrenom(String prenom){
        
            this.prenomTextField2.setText(prenom);
            
        }
        
        public void setEmail(String email){
        
             this.emailTextField3.setText(email);
            
        }
        
        public void setCommune(String commune){
        
             this.communeTextField1.setText(commune);
            
        }
        
        public String getNom(){
        
            return this.nomTextField1.getText();
        
        }
        
        public String getPrenom(){
        
            return this.prenomTextField2.getText();
            
        }
        
        public String getEmail(){
        
            return this.emailTextField3.getText();
            
        }
        public String getCommune(){
        
            return this.communeTextField1.getText();
            
        }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModifDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModifDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModifDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModifDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ModifDialog dialog = new ModifDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel communeLabel4;
    private javax.swing.JTextField communeTextField1;
    private javax.swing.JTextField emailTextField3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField nomTextField1;
    private javax.swing.JTextField prenomTextField2;
    private javax.swing.JToggleButton valideModifToggleButton1;
    // End of variables declaration//GEN-END:variables
}
